name: "Beem Cloud Custom"
url: "https://github.com/cyril-cros/custom-hass-addon/tree/main/beem-cloud-custom"
description: "Connect your Beem Energy Battery to Home Assistant ⚡️"
services:
  - "mqtt:want"
version: "0.0.1"
homeassistant_api: true
image: cyril-cros/beem-cloud-custom-{arch}
slug: "beem-cloud-custom"
init: false
discovery:
  - "mqtt"
options:
  beem_email: ""
  beem_password: ""
  refresh_interval: 1
  debug: false
  start_delayseconds: 1
schema:
  beem_email: email
  beem_password: password
  refresh_interval: int
  debug: bool
  override_mqtt_user: str?
  override_mqtt_password: password?
  override_mqtt_server: str?
  override_mqtt_port: port?
  start_delayseconds: int?
arch:
  - amd64
  - aarch64
  - armv7